name: my-app
services:
  - name: backend
    github:
      branch: main
      deploy_on_push: true
      repo: applemang/cursor-test
    source_dir: backend
    dockerfile_path: Dockerfile.backend
    http_port: 8000
    instance_size_slug: basic-xxs
    envs:
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
      - key: SECRET_KEY
        type: SECRET
        value: your-secret-key-here
      - key: CORS_ORIGINS
        value: ${APP_URL}
    routes:
      - path: /api

  - name: frontend
    github:
      branch: main
      deploy_on_push: true
      repo: applemang/cursor-test
    source_dir: frontend
    dockerfile_path: Dockerfile.frontend
    http_port: 3000
    instance_size_slug: basic-xxs
    envs:
      - key: REACT_APP_API_URL
        value: ${APP_URL}/api
    routes:
      - path: /

databases:
  - engine: PG
    name: db
    num_nodes: 1
    size: db-s-dev-database
    version: "12" 